### ISSUE TITLE
Segfaults at extremely low emulated resolutions

### ISSUE THREAD

**Issue by samis** [alakazard12/OCEmulator-Qt#3]
If, within OpenOS you set either of the resolution values to 1, then the emulator will segfault and terminate. This is more noticeable with the first value than the second in my opinion.

**Comment by alakazard12** [comment]
When I tried reproducing this it didn't segfault immediately after changing the resolution, is this the same case for you? The segfault happens in Lua so it could be a problem with the allocator; I'll try using the default allocator and see if that fixes it later.

**Comment by samis** [comment]
It doesn't segfault instantly, no. There is a noticeable point of it being at 1x1 res before it happens. Additionally, resolution 2 1 seems to take longer to crash than resolution 1 <x>

**Comment by alakazard12** [comment]
A bug in the gpu.get() function may have been causing it. I pushed an update but I haven't had time to test it.
